backend:
  container_name: open_loyalty_backend
  build: ./backend
  links:
    - elk
    - db
  volumes_from:
    - oloy-sync:rw
  ports:
    - "8181:80"
  extra_hosts:
    - "web:127.0.0.1"

elk:
  container_name: open_loyalty_elk
  image: elasticsearch:2.2
db:
  container_name: open_loyalty_postgresql
  image: postgres
  environment:
    - POSTGRES_DB=openloyalty
    - POSTGRES_USER=openloyalty
    - POSTGRES_PASSWORD=openloyalty
